# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno and run tests across stable and nightly builds on Windows, Ubuntu and macOS.
# For more information see: https://github.com/denolib/setup-deno

name: Deno

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-format:
    runs-on: ${{ matrix.os }} # runs a test on Ubuntu, Windows and macOS

    strategy:
      matrix:
        deno: ["v1.x"]
        os: [ubuntu-latest]

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1.1.0
        with:
          deno-version: ${{ matrix.deno }}

      - name: Run Deno Check Formatting
        run: deno fmt --check

  test:
    runs-on: ${{ matrix.os }} # runs a test on Ubuntu, Windows and macOS

    strategy:
      matrix:
        deno: ["v1.x"]
        # os: [macOS-latest, windows-latest, ubuntu-latest]
        os: [ubuntu-latest]

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1.1.0
        with:
          deno-version: ${{ matrix.deno }}

      - name: Run Deno Tests
        run: deno test --doc --parallel --coverage=coverage

      - name: Generate Coverage
        run: deno coverage --unstable ./coverage --lcov > ./coverage/lcov.info

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          flag-name: run-${{ matrix.deno }}-${{ matrix.os }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base-path: /
